// fetch books
export const FETCH_BOOKS_PENDING = 'FETCH_BOOKS_PENDING'
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
export const FETCH_BOOKS_FAILED = 'FETCH_BOOKS_FAILED'
// fetch book
export const FETCH_BOOK_PENDING = 'FETCH_BOOK_PENDING'
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS'
export const FETCH_BOOK_FAILED = 'FETCH_BOOK_FAILED'
// create book
export const CREATE_BOOK_PENDING = 'CREATE_BOOK_PENDING'
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS'
export const CREATE_BOOK_FAILED = 'CREATE_BOOK_FAILED'

// create review
export const CREATE_BOOK_REVIEW_PENDING = 'CREATE_BOOK_REVIEW_PENDING'
export const CREATE_BOOK_REVIEW_SUCCESS = 'CREATE_BOOK_REVIEW_SUCCESS'
export const CREATE_BOOK_REVIEW_FAILED = 'CREATE_BOOK_REVIEW_FAILED'
// update review
export const UPDATE_BOOK_REVIEW_PENDING = 'UPDATE_BOOK_REVIEW_PENDING'
export const UPDATE_BOOK_REVIEW_SUCCESS = 'UPDATE_BOOK_REVIEW_SUCCESS'
export const UPDATE_BOOK_REVIEW_FAILED = 'UPDATE_BOOK_REVIEW_FAILED'

// book search
export const SET_SEARCH_TERM_PENDING = 'SET__SEARCH_TERM_PENDING'
export const SET_SEARCH_TERM_SUCCESS = 'SET_SEARCH_TERM_SUCCESS'
export const SET_SEARCH_TERM_FAILED = 'SET_SEARCH_TERM_FAILED'
