name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Linting
        run: |
          npm run lint:fix
      - name: Jest
        run: npm test
      - name: Cypress
        run: npm run cypress:run
      - name: Build production
        run: npm run build
